export const jobData = [
    {
      id: 1,
      title: "Senior Frontend Developer",
      company: "TechCorp",
      location: "New York, NY",
      salary: "$120k - $150k",
      type: "Remote",
      experience: "5+ years",
      logo: "/esewa.webp",
      postedAt: "2 days ago",
    },
    {
      id: 2,
      title: "Full Stack Engineer",
      company: "InnovateSoft",
      location: "San Francisco, CA",
      salary: "$130k - $160k",
      type: "Hybrid",
      experience: "3-5 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "1 week ago",
    },
    {
      id: 3,
      title: "UX/UI Designer",
      company: "DesignHub",
      location: "Austin, TX",
      salary: "$90k - $120k",
      type: "On-site",
      experience: "2-4 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "3 days ago",
    },
    {
      id: 4,
      title: "DevOps Engineer",
      company: "CloudTech",
      location: "Seattle, WA",
      salary: "$140k - $170k",
      type: "Remote",
      experience: "4+ years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "Just now",
    },
    {
      id: 5,
      title: "Product Manager",
      company: "ProductWave",
      location: "Boston, MA",
      salary: "$110k - $140k",
      type: "Hybrid",
      experience: "3+ years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "5 days ago",
    },
    {
      id: 6,
      title: "Data Scientist",
      company: "DataInsight",
      location: "Chicago, IL",
      salary: "$125k - $155k",
      type: "Remote",
      experience: "3-6 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "1 week ago",
    },
    {
      id: 7,
      title: "Backend Developer",
      company: "ServerStack",
      location: "Denver, CO",
      salary: "$115k - $145k",
      type: "On-site",
      experience: "4+ years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "2 weeks ago",
    },
    {
      id: 8,
      title: "Mobile App Developer",
      company: "AppWorks",
      location: "Los Angeles, CA",
      salary: "$100k - $130k",
      type: "Hybrid",
      experience: "2-5 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "3 days ago",
    },
    {
      id: 9,
      title: "QA Engineer",
      company: "QualityTech",
      location: "Portland, OR",
      salary: "$85k - $110k",
      type: "Remote",
      experience: "2-4 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "1 day ago",
    },
    {
      id: 10,
      title: "Technical Project Manager",
      company: "ProjectPro",
      location: "Atlanta, GA",
      salary: "$105k - $135k",
      type: "Hybrid",
      experience: "4-7 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "4 days ago",
    },
    {
      id: 11,
      title: "Systems Architect",
      company: "ArchSystems",
      location: "Washington, DC",
      salary: "$140k - $180k",
      type: "Remote",
      experience: "7+ years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "1 week ago",
    },
    {
      id: 12,
      title: "Blockchain Developer",
      company: "ChainTech",
      location: "Miami, FL",
      salary: "$130k - $160k",
      type: "Remote",
      experience: "3-5 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "3 days ago",
    },
    {
      id: 13,
      title: "AI/ML Engineer",
      company: "IntelliSys",
      location: "San Jose, CA",
      salary: "$150k - $190k",
      type: "On-site",
      experience: "5+ years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "2 weeks ago",
    },
    {
      id: 14,
      title: "Network Security Specialist",
      company: "SecureNet",
      location: "Dallas, TX",
      salary: "$110k - $140k",
      type: "Hybrid",
      experience: "4-6 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "5 days ago",
    },
    {
      id: 15,
      title: "Cloud Solutions Architect",
      company: "CloudArch",
      location: "Raleigh, NC",
      salary: "$130k - $160k",
      type: "Remote",
      experience: "5-8 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "1 week ago",
    },
    {
      id: 16,
      title: "Frontend Team Lead",
      company: "UIExperts",
      location: "Minneapolis, MN",
      salary: "$125k - $155k",
      type: "Hybrid",
      experience: "6+ years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "3 days ago",
    },
    {
      id: 17,
      title: "Database Administrator",
      company: "DataSystems",
      location: "Phoenix, AZ",
      salary: "$100k - $130k",
      type: "On-site",
      experience: "3-5 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "2 days ago",
    },
    {
      id: 18,
      title: "Technical Writer",
      company: "DocuTech",
      location: "Remote",
      salary: "$80k - $100k",
      type: "Remote",
      experience: "2-4 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "1 week ago",
    },
    {
      id: 19,
      title: "IT Project Coordinator",
      company: "TechCoord",
      location: "Detroit, MI",
      salary: "$75k - $95k",
      type: "Hybrid",
      experience: "1-3 years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "4 days ago",
    },
    {
      id: 20,
      title: "Software Engineering Manager",
      company: "CodeLead",
      location: "San Diego, CA",
      salary: "$160k - $200k",
      type: "On-site",
      experience: "8+ years",
      logo: "/placeholder.svg?height=64&width=64",
      postedAt: "2 weeks ago",
    },
  ]
  